import random
to_guess = random.randint(1, 10)
attemps = 3
print(to_guess)

print("WELCOME TO THE GUESSING GAME PUNK")
print("Try to guess the number generated by the computer!\n")

while attemps > 0:
    print(f"You have {attemps} attemps left")

    try:
        user_input = int(input("Your number: "))
    except:
        print("You need to enter a number punk! Don't be a stupid. Sorry :V :)")
        print("Anyway, you've lost an attemp :)")
        user_input = 0

    if user_input == to_guess:
        print("Congratulations! You've won")
        break

    print("** Wrong number! **")
    attemps -= 1
    if user_input > to_guess:
        print("** You need a smaller number! **")
    else:
        print("** You need a bigger number! **")
    print("----------------------------------\n")

if attemps==0:
    print("Sorry :( You've lost the game")
